PYODBC_MSSQL_CONNECTION_STRING = "DRIVER={ODBC Driver 17 for SQL Server};SERVER=%s;DATABASE=%s;UID=%s;PWD=%s"
#PYODBC_MSSQL_CONNECTION_STRING = "DRIVER={SQL Server};SERVER=%s;DATABASE=%s;UID=%s;PWD=%s"
PYODBC_MYSQL_CONNECTION_STRING = "DRIVER={MySQL ODBC 8.0 Unicode Driver};SERVER=%s;DATABASE=%s;UID=%s;PWD=%s"
PYMONGO_CONNECTION_STRING = "mongodb://{server}:27017/"
#PYMONGO_CONNECTION_STRING = "mongodb+srv://{username}:{password}@{server}/{db_name}"

